#!/bin/bash

# clean up *all* the auto-generated stuff, i.e. compiled code, generated documentation, python cached files, test data...

# remove compiled stuff
# rm tenpy/linalg/{*.c,*.cpp,*.so,*.html}
find tenpy/linalg/ -name "*.c" -o -name "*.cpp" -o -name "*.so" -o -name "*.html" -delete
test -d build && rm -r build

# clean-up generated documentation
test -d doc/sphinx_build && rm -r doc/sphinx_build

# clean-up data generated by tests
test -d tests/export_import_test/data && rm -r tests/export_import_test/data

# remove python cached files. They might give problems if you modified some files and the date of the file wasn't updated.
find . -name "*.pyc" -delete
find . -name "__pycache__" -delete
