#!/bin/bash

echo "Clean up all the compiled/autogenerated stuff in the cyten repository, and possibly more."
read -p "Are you sure? Type 'y' to confirm: " -n 1
echo
if [ "$REPLY" != "y" ]; then
    echo "Abort"
    exit 1
fi
echo "The following files and folders got removed"

rm_dir() {
	test -d "$1" && echo "$1/" && rm -r "$1"
}

rm_files() {
	for file in "$@"
	do
		test -f "$file" && echo "$file" && rm "$file"
	done
}

# remove compiled package
rm_dir "build"

# remove testing caches
rm_dir ".pytest_cache"
rm_dir "tests/.pytest_cache"
rm_dir "tests/python_tests/.pytest_cache"

# remove built documentation
rm_dir "doc/examples"
rm_dir "doc/toycode_stubs"
rm_dir "doc/reference"
rm_dir "doc/sphinx_build"

# remove python cached files. They might give problems if you modified some files and the date of the file wasn't updated.
find . -name "*.pyc" -delete
find . -name "__pycache__" -print -delete
