name: Run Pytest (old numpy)
on:
  # pushes to main
  push:
    branches:
      - main


jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    env:
      # make pytest output in color
      PY_COLORS: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - numpy-version: "1.23"
            python-version: "3.11"
          - numpy-version: "1.24"
            python-version: "3.11"
          - numpy-version: "1.25"
            python-version: "3.11"
          - numpy-version: "1.26"
            python-version: "3.12"
          - numpy-version: "1.26.4"
            python-version: "3.12"
          - numpy-version: "2.0"
            python-version: "3.12"
          - numpy-version: "2.0"
            python-version: "3.13"
          - numpy-version: "2.1"
            python-version: "3.13"
          - numpy-version: "2.2"
            python-version: "3.13"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools build
        python -m pip install --upgrade numpy==${{ matrix.numpy-version }}
        python -m pip install --upgrade pytest
    
    - name: Build and install tenpy
      # also installs extra dependencies defined in pyproject.toml
      run: |
        python -m build .
        python -m pip install ".[io, test, extra]"
        bash ./compile.sh
    
    - name: Show tenpy config
      run: |
        python -c "import tenpy; tenpy.show_config()"
    
    - name: Run pytest
      # configuration in pyproject.toml
      # Note: This runs in the repo root directory, which contains the uncompiled tenpy package.
      #       To use the version we just installed, it is important to run `pytest`
      #       instead of `python -m pytest`.
      run: pytest
